# /* wallust template - colors-hyprland */

$background = rgb(2C2C2D)
$foreground = rgb(F8D4C7)
$color0 = rgb(515151)
$color1 = rgb(212123)
$color2 = rgb(252527)
$color3 = rgb(4F3530)
$color4 = rgb(4A5256)
$color5 = rgb(5D696D)
$color6 = rgb(B16448)
$color7 = rgb(EDBAA7)
$color8 = rgb(A68275)
$color9 = rgb(2C2C2E)
$color10 = rgb(313234)
$color11 = rgb(6A4740)
$color12 = rgb(636E72)
$color13 = rgb(7C8C91)
$color14 = rgb(EC8560)
$color15 = rgb(EDBAA7)
