# /* wallust template - colors-hyprland */ 

$background = rgb(111010)
$foreground = rgb(F7ECD4)
$color0 = rgb(393838)
$color1 = rgb(50595E)
$color2 = rgb(7D5119)
$color3 = rgb(AB7141)
$color4 = rgb(528974)
$color5 = rgb(56915E)
$color6 = rgb(AF9764)
$color7 = rgb(EBDCBA)
$color8 = rgb(A59A82)
$color9 = rgb(6A777D)
$color10 = rgb(A76C21)
$color11 = rgb(E49656)
$color12 = rgb(6DB79B)
$color13 = rgb(73C17D)
$color14 = rgb(E9CA85)
$color15 = rgb(EBDCBA)
