# /* wallust template - colors-hyprland */ 

$background = rgb(1D1618)
$foreground = rgb(FCF4E0)
$color0 = rgb(453C3E)
$color1 = rgb(A67068)
$color2 = rgb(BA6B5C)
$color3 = rgb(9F7B73)
$color4 = rgb(33A89B)
$color5 = rgb(BC9471)
$color6 = rgb(B9A87C)
$color7 = rgb(F3E7CA)
$color8 = rgb(AAA28D)
$color9 = rgb(DE968A)
$color10 = rgb(F88F7B)
$color11 = rgb(D4A49A)
$color12 = rgb(44E0CE)
$color13 = rgb(FBC597)
$color14 = rgb(F7E1A6)
$color15 = rgb(F3E7CA)
