# /* wallust template - colors-hyprland */ 

$background = rgb(141314)
$foreground = rgb(FCF7CF)
$color0 = rgb(3C3B3B)
$color1 = rgb(394842)
$color2 = rgb(7D4131)
$color3 = rgb(0B7093)
$color4 = rgb(107398)
$color5 = rgb(B87938)
$color6 = rgb(B9AF58)
$color7 = rgb(F3ECB2)
$color8 = rgb(AAA57C)
$color9 = rgb(4C6058)
$color10 = rgb(A75741)
$color11 = rgb(0F95C4)
$color12 = rgb(1599CA)
$color13 = rgb(F6A24B)
$color14 = rgb(F7E976)
$color15 = rgb(F3ECB2)
