# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# Workspace 1 — Terminal
windowrule = workspace 1, match:class ^(kitty|alacritty|wezterm|foot|ghostty)$

# Workspace 2 — IDEs
windowrule = workspace 2, match:class ^(VSCode|code|code-oss)$
windowrule = workspace 2, match:class ^(cursor|Cursor)$
windowrule = workspace 2, match:class ^(jetbrains-idea|jetbrains-webstorm|jetbrains-pycharm)$

# Workspace 3
windowrule = workspace 3, match:class ^(zen|firefox|Firefox)$

# # Workspace 4
windowrule = workspace 4, match:class ^(chromium|google-chrome|brave-browser)$
# windowrule = workspace 4, match:class ^(insomnia|Insomnia|postman|Postman)$
# windowrule = workspace 4, match:class ^(beekeeper-studio|dbeaver)$
# windowrule = workspace 4, match:title .*TablePlus.*

# Workspace 5 — File Manager
windowrule = workspace 5, match:class ^(thunar|nautilus|nemo|pcmanfm)$

# Workspace 6 — Communication
windowrule = workspace 6, match:class ^(discord|Discord|slack|Slack)$
windowrule = workspace 6, match:title .*Telegram.*

# Workspace 7 — Monitoring / Containers
windowrule = workspace 7, match:title ^(btop|lazydocker|docker-desktop)$

# Workspace 8 — Notes
windowrule = workspace 8, match:class ^(obsidian|Obsidian)$

