# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# Workspace 1 — Terminal
windowrule = workspace 1, match:tag terminal

# Workspace 2 — IDEs
# windowrule = workspace 2, maximize 1, match:class ^(VSCode|code|code-oss)$
# windowrule = workspace 2, maximize 1, match:class ^(cursor|Cursor)$
# windowrule = workspace 2, maximize 1, match:class ^(jetbrains-idea|jetbrains-webstorm|jetbrains-pycharm)$
windowrule = workspace 2, match:tag projects
windowrule = workspace 2, float 1, match:class ^(Emulator)$

# Workspace 3
windowrule = workspace 3, match:class ^(zen|firefox|Firefox)$

# # Workspace 4
windowrule = workspace 4, match:class ^(chromium|google-chrome|brave-browser)$
# windowrule = workspace 4, match:class ^(insomnia|Insomnia|postman|Postman)$
# windowrule = workspace 4, match:class ^(beekeeper-studio|dbeaver)$
# windowrule = workspace 4, match:title .*TablePlus.*

# Workspace 5 — File Manager
windowrule = workspace 5, match:tag file-manager

# Workspace 6 — Communication
windowrule = workspace 6, match:tag im

# Workspace 7 — Monitoring / Containers
windowrule = workspace 7, match:title ^(btop|lazydocker|docker-desktop)$

# Workspace 8 — Notes
windowrule = workspace 8, match:class ^(obsidian|Obsidian)$
