# /* wallust template - colors-kitty */

foreground         #F8D4C7
background         #2C2C2D
cursor             #95837E

active_tab_foreground     #2C2C2D
active_tab_background     #F8D4C7
inactive_tab_foreground   #F8D4C7
inactive_tab_background   #2C2C2D

active_border_color   #F8D4C7
inactive_border_color #2C2C2D
bell_border_color     #212123

color0      #515151
color1		#212123
color2		#252527
color3		#4F3530
color4		#4A5256
color5		#5D696D
color6		#B16448
color7		#EDBAA7
color8		#A68275
color9		#2C2C2E
color10		#313234
color11		#6A4740
color12		#636E72
color13		#7C8C91
color14		#EC8560
color15		#EDBAA7
