# /* wallust template - colors-kitty */

foreground         #DCD5D7
background         #883E2F
cursor             #B37A63

active_tab_foreground     #883E2F
active_tab_background     #DCD5D7
inactive_tab_foreground   #DCD5D7
inactive_tab_background   #883E2F

active_border_color   #DCD5D7
inactive_border_color #883E2F
bell_border_color     #B9A87C

color0      #AEA3A6
color1		#B9A87C
color2		#BC9471
color3		#33A89B
color4		#9F7B73
color5		#BA6B5C
color6		#A67068
color7		#6F654B
color8		#AD9D74
color9		#F7E1A6
color10		#FBC597
color11		#44E0CE
color12		#D4A49A
color13		#F88F7B
color14		#DE968A
color15		#F3E7CA
