# /* wallust template - colors-kitty */

foreground         #D6D6D7
background         #131321
cursor             #4993A0

active_tab_foreground     #131321
active_tab_background     #D6D6D7
inactive_tab_foreground   #D6D6D7
inactive_tab_background   #131321

active_border_color   #D6D6D7
inactive_border_color #131321
bell_border_color     #A3A099

color0      #A4A4A7
color1		#A3A099
color2		#A29C94
color3		#2096AB
color4		#1F95AA
color5		#2494AC
color6		#2491A7
color7		#62605C
color8		#98958E
color9		#D9D5CB
color10		#D8D0C6
color11		#2BC8E4
color12		#2AC7E3
color13		#30C6E5
color14		#2FC1DF
color15		#E3E2DD
