### Variables

# Logo key. Use Mod1 for Alt.
set $mod Mod4
set $alt Mod1

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

set $send-notify exec --no-startup-id notify-send -u low -h string:x-canonical-private-synchronous:swayconfig

set $wezterm ~/.config/sway/scripts/wezterm
# set $alacritty ~/.config/sway/scripts/alacritty
set $foot ~/.config/sway/scripts/foot
set $kitty ~/.config/sway/scripts/kitty
set $volume ~/.config/sway/scripts/volume
set $backlight ~/.config/sway/scripts/brightness
set $screenshot ~/.config/sway/scripts/screenshot
set $lockscreen ~/.config/sway/scripts/lockscreen
set $wlogout ~/.config/sway/scripts/wlogout
# set $colorpicker ~/.config/sway/scripts/colorpicker
set $files thunar
# set $editor geany
set $browser firefox

set $rofi_bluetooth ~/.config/sway/scripts/rofi_bluetooth
set $rofi_launcher ~/.config/sway/scripts/rofi_launcher
set $rofi_music ~/.config/sway/scripts/rofi_music
set $rofi_powermenu ~/.config/sway/scripts/rofi_powermenu
set $rofi_runner ~/.config/sway/scripts/rofi_runner
set $rofi_screenshot ~/.config/sway/scripts/rofi_screenshot
set $rofi_network ~/.config/sway/scripts/rofi_network
set $rofi_asroot ~/.config/sway/scripts/rofi_asroot

set $wofi_menu ~/.config/sway/scripts/wofi_menu
set $wofi_powermenu ~/.config/sway/scripts/wofi_powermenu

set $open_in_wezterm wezterm

