title_align center
for_window [floating] move position center
for_window [floating] resize set 800 500

for_window [window_role="pop-up"] floating enable
for_window [window_role="task_dialog"] floating enable

for_window [app_id="wezterm-float|foot-float|kitty-float"] floating enable, resize set 800 500
for_window [app_id="xfce-polkit"] floating enable
for_window [app_id="Yad" instance="yad"] floating disable
for_window [app_id="xdg-desktop-portal-gtk"] floating enable, resize set 1200 800

for_window [shell=".*"] focus
for_window [app_id="firefox"] opacity 0.9
for_window [app_id="firefox-developer-edition"] opacity 0.9

# sway config for Inkscape Windows
# for_window [title="Text and Font"]        floating toggle
# for_window [title="Transform"]            floating toggle
# for_window [title="Align and Distribute"] floating toggle
# for_window [title="Path Effects"]         floating toggle
# for_window [title="Export PNG Image"]     floating toggle
# for_window [title="Fill and Stroke"]      floating toggle
# for_window [title="Drop Shadow"]          floating toggle
# for_window [title="Blur"]                 floating toggle

# assign [app_id="foot"] → workspace number 1
# assign [class="firefox"] → workspace number 2
# assign [app_id="thunar"] → workspace number 3
# assign [app_id="geany"] → workspace number 4

# for_window [window_role="pop-up"] floating enable
# for_window [window_role="task_dialog"] floating enable
# for_window [app_id="alacritty-float|foot-float|kitty-float"] floating enable
# for_window [app_id="yad|nm-connection-editor|pavucontrol"] floating enable
# for_window [app_id="xfce-polkit|kvantummanager|qt5ct"] floating enable
# for_window [app_id="io.calamares.calamares"] floating enable
# for_window [title="Archcraft Installer"] floating enable
# for_window [class="Yad|feh|Viewnior|Gpicview|Gimp|MPlayer"] floating enable
# for_window [class="VirtualBox Manager|qemu|Qemu-system-x86_64"] floating enable

